/**
 * Biome selection and terrain-shape blending.
 *
 * The generator is a small climate model rather than a lookup on one height
 * noise:
 *
 *  1. Four independent *shape* fields (continentalness, erosion, hilliness and
 *     a ridge field) decide the raw landform.
 *  2. Two independent *climate* fields (temperature and moisture), warped and
 *     biased by altitude, place the column in climate space.
 *  3. Every land biome sits at a point in that climate space. Column height is
 *     the weighted blend of each biome's own height profile, weighted by
 *     inverse-square distance in climate space. That blend is what removes the
 *     hard cliff you otherwise get where a desert meets a forest — the terrain
 *     shape morphs continuously even though the surface block changes at a
 *     discrete boundary.
 *  4. Ocean, beach and mountain classification happens *after* the height is
 *     known, because those are consequences of elevation rather than climate.
 *
 * Every function here is a pure function of (seed, x, z), so two neighbouring
 * chunks generated by two different workers agree exactly on their shared edge.
 *
 * Worker-safe.
 */

import { SEA_LEVEL, WORLD_HEIGHT } from '../config/GameConfig.js';
import { clamp, clamp01, lerp, smoothstep } from '../utils/MathUtils.js';
import { NoiseSet } from './Noise.js';
import { Block } from './BlockTypes.js';
import { NETHER_BIOME_DEFINITIONS } from './NetherBiomes.js';

/** @enum {number} */
export const Biome = Object.freeze({
  OCEAN: 0,
  BEACH: 1,
  PLAINS: 2,
  FOREST: 3,
  BIRCH_FOREST: 4,
  TAIGA: 5,
  SNOWY_PLAINS: 6,
  DESERT: 7,
  SAVANNA: 8,
  ROCKY_HILLS: 9,
  MOUNTAINS: 10,
  SNOWY_PEAKS: 11,
  FROZEN_OCEAN:12, COLD_OCEAN:13, LUKEWARM_OCEAN:14, WARM_OCEAN:15, DEEP_OCEAN:16,
  RIVER:17, FROZEN_RIVER:18, STONY_SHORE:19, JUNGLE:20, BAMBOO_JUNGLE:21,
  SPARSE_JUNGLE:22, SWAMP:23, MANGROVE_SWAMP:24, MUSHROOM_FIELDS:25, BADLANDS:26,
  WOODED_BADLANDS:27, ERODED_BADLANDS:28, CHERRY_GROVE:29, ICE_SPIKES:30,
  MEADOW:31, GROVE:32, WINDSWEPT_HILLS:33, DARK_FOREST:34, FLOWER_FOREST:35,
  OLD_GROWTH_PINE_TAIGA:36, OLD_GROWTH_SPRUCE_TAIGA:37, SUNFLOWER_PLAINS:38,
  SAVANNA_PLATEAU:39, SNOWY_TAIGA:40, LUSH_CAVES:41, DRIPSTONE_CAVES:42,
  DEEP_DARK:43, UNDERGROUND_LAKES:44,
});

/** Tree archetypes the structure generator knows how to build. */
export const TreeType = Object.freeze({
  NONE: 'none',
  OAK: 'oak',
  BIRCH: 'birch',
  SPRUCE: 'spruce',
  ACACIA: 'acacia',
  CACTUS: 'cactus',
});

const EXTRA_BIOMES = Object.freeze([
  [Biome.FROZEN_OCEAN,'Frozen Ocean',-.95,.45,SEA_LEVEL-14,.3,.5,Block.ICE,Block.SAND,TreeType.NONE,0,0,0,true,[165,200,205]],
  [Biome.COLD_OCEAN,'Cold Ocean',-.55,.7,SEA_LEVEL-13,.32,.55,Block.SAND,Block.GRAVEL,TreeType.NONE,0,0,0,false,[115,170,145]],
  [Biome.LUKEWARM_OCEAN,'Lukewarm Ocean',.45,.75,SEA_LEVEL-11,.34,.6,Block.SAND,Block.SAND,TreeType.NONE,0,0,0,false,[92,185,118]],
  [Biome.WARM_OCEAN,'Warm Ocean',.9,.8,SEA_LEVEL-10,.3,.5,Block.SAND,Block.SAND,TreeType.NONE,0,0,0,false,[74,198,105]],
  [Biome.DEEP_OCEAN,'Deep Ocean',0,.9,SEA_LEVEL-24,.25,.8,Block.GRAVEL,Block.STONE,TreeType.NONE,0,0,0,false,[90,154,132]],
  [Biome.RIVER,'River',.15,.85,SEA_LEVEL-1,.25,.45,Block.SAND,Block.CLAY,TreeType.NONE,0,.3,0,false,[105,188,113]],
  [Biome.FROZEN_RIVER,'Frozen River',-.9,.75,SEA_LEVEL-1,.22,.4,Block.ICE,Block.GRAVEL,TreeType.NONE,0,0,0,true,[170,205,200]],
  [Biome.STONY_SHORE,'Stony Shore',-.2,.15,SEA_LEVEL+2,.7,.9,Block.STONE,Block.STONE,TreeType.NONE,0,.2,0,false,[125,160,120]],
  [Biome.JUNGLE,'Jungle',.85,.82,SEA_LEVEL+9,.9,1,Block.GRASS,Block.DIRT,TreeType.OAK,12,18,5,false,[70,170,55]],
  [Biome.BAMBOO_JUNGLE,'Bamboo Jungle',.78,.95,SEA_LEVEL+10,.8,.9,Block.GRASS,Block.DIRT,TreeType.OAK,9,24,2,false,[75,180,62]],
  [Biome.SPARSE_JUNGLE,'Sparse Jungle',.8,.48,SEA_LEVEL+8,.7,.75,Block.GRASS,Block.DIRT,TreeType.OAK,4,18,3,false,[100,181,67]],
  [Biome.SWAMP,'Swamp',.55,.95,SEA_LEVEL+2,.25,.55,Block.GRASS,Block.CLAY,TreeType.OAK,4,12,2,false,[78,135,72]],
  [Biome.MANGROVE_SWAMP,'Mangrove Swamp',.78,1,SEA_LEVEL+2,.28,.6,Block.GRASS,Block.CLAY,TreeType.OAK,7,14,1,false,[68,126,65]],
  [Biome.MUSHROOM_FIELDS,'Mushroom Fields',.3,.9,SEA_LEVEL+7,.55,.65,Block.GRASS,Block.DIRT,TreeType.NONE,0,6,5,false,[124,170,108]],
  [Biome.BADLANDS,'Badlands',.95,-.75,SEA_LEVEL+12,1.15,1.1,Block.RED_SAND,Block.RED_SAND,TreeType.NONE,0,.2,0,false,[190,155,80]],
  [Biome.WOODED_BADLANDS,'Wooded Badlands',.82,-.5,SEA_LEVEL+18,1.25,1.15,Block.RED_SAND,Block.STONE,TreeType.OAK,2,2,0,false,[170,148,82]],
  [Biome.ERODED_BADLANDS,'Eroded Badlands',1,-.95,SEA_LEVEL+24,1.8,1.4,Block.RED_SAND,Block.STONE,TreeType.NONE,0,0,0,false,[198,150,72]],
  [Biome.CHERRY_GROVE,'Cherry Grove',-.05,.62,SEA_LEVEL+18,1,.75,Block.GRASS,Block.DIRT,TreeType.OAK,6,9,10,false,[136,190,110]],
  [Biome.ICE_SPIKES,'Ice Spikes',-1,-.25,SEA_LEVEL+13,1.15,1.25,Block.SNOW_BLOCK,Block.ICE,TreeType.NONE,0,0,0,true,[190,214,220]],
  [Biome.MEADOW,'Meadow',-.15,.18,SEA_LEVEL+16,.85,.55,Block.GRASS,Block.DIRT,TreeType.OAK,.5,18,12,false,[120,200,92]],
  [Biome.GROVE,'Grove',-.62,.35,SEA_LEVEL+22,1.1,.8,Block.SNOWY_GRASS,Block.DIRT,TreeType.SPRUCE,6,3,0,true,[140,175,145]],
  [Biome.WINDSWEPT_HILLS,'Windswept Hills',-.25,-.35,SEA_LEVEL+26,1.8,1.35,Block.STONE,Block.STONE,TreeType.SPRUCE,1,2,0,false,[118,160,112]],
  [Biome.DARK_FOREST,'Dark Forest',.1,.78,SEA_LEVEL+9,.75,.8,Block.GRASS,Block.DIRT,TreeType.OAK,11,6,1,false,[62,135,54]],
  [Biome.FLOWER_FOREST,'Flower Forest',.12,.55,SEA_LEVEL+8,.65,.55,Block.GRASS,Block.DIRT,TreeType.OAK,5,10,18,false,[118,190,78]],
  [Biome.OLD_GROWTH_PINE_TAIGA,'Old Growth Pine Taiga',-.48,.68,SEA_LEVEL+13,1.05,1,Block.GRASS,Block.DIRT,TreeType.SPRUCE,11,4,.2,false,[88,148,94]],
  [Biome.OLD_GROWTH_SPRUCE_TAIGA,'Old Growth Spruce Taiga',-.65,.78,SEA_LEVEL+14,1.1,1.05,Block.GRASS,Block.DIRT,TreeType.SPRUCE,13,3,0,false,[82,142,90]],
  [Biome.SUNFLOWER_PLAINS,'Sunflower Plains',.3,-.02,SEA_LEVEL+6,.5,.45,Block.GRASS,Block.DIRT,TreeType.OAK,.4,16,9,false,[152,202,82]],
  [Biome.SAVANNA_PLATEAU,'Savanna Plateau',.82,-.42,SEA_LEVEL+18,1,.75,Block.GRASS,Block.DIRT,TreeType.ACACIA,2,13,.5,false,[170,184,88]],
  [Biome.SNOWY_TAIGA,'Snowy Taiga',-.86,.52,SEA_LEVEL+10,.8,.8,Block.SNOWY_GRASS,Block.DIRT,TreeType.SPRUCE,8,2,0,true,[145,180,158]],
  [Biome.LUSH_CAVES,'Lush Caves',.35,.9,28,.4,.8,Block.CLAY,Block.STONE,TreeType.NONE,0,10,4,false,[76,176,78],true],
  [Biome.DRIPSTONE_CAVES,'Dripstone Caves',.2,-.35,24,.6,1.1,Block.STONE,Block.TUFF,TreeType.NONE,0,0,0,false,[115,132,102],true],
  [Biome.DEEP_DARK,'Deep Dark',-.2,.1,8,.25,.7,Block.DEEPSLATE,Block.DEEPSLATE,TreeType.NONE,0,0,0,false,[45,78,75],true],
  [Biome.UNDERGROUND_LAKES,'Underground Lakes',.1,.65,20,.3,.75,Block.CLAY,Block.STONE,TreeType.NONE,0,0,0,false,[72,120,105],true],
].map(([id,name,temperature,moisture,baseHeight,amplitude,roughness,surface,subsurface,tree,treeDensity,grassDensity,flowerDensity,snowy,grassTint,underground=false])=>Object.freeze({id,name,temperature,moisture,baseHeight,amplitude,roughness,surface,subsurface,subsurfaceDepth:4,tree,treeDensity,grassDensity,flowerDensity,snowy,grassTint,underground})));

/**
 * @typedef {Object} BiomeDefinition
 * @property {number} id
 * @property {string} name
 * @property {number} temperature Climate-space X, in `[-1, 1]`.
 * @property {number} moisture Climate-space Y, in `[-1, 1]`.
 * @property {number} baseHeight Height this biome pulls the terrain towards.
 * @property {number} amplitude Multiplier on the shared landform relief.
 * @property {number} roughness Extra small-scale noise amplitude.
 * @property {number} surface Surface block id.
 * @property {number} subsurface Block id beneath the surface.
 * @property {number} subsurfaceDepth Thickness of the subsurface layer.
 * @property {string} tree
 * @property {number} treeDensity Expected trees per chunk.
 * @property {number} grassDensity Expected grass/fern clumps per chunk.
 * @property {number} flowerDensity Expected flowers per chunk.
 * @property {boolean} snowy
 * @property {[number,number,number]} grassTint Foliage tint, 0..255.
 */

/**
 * Land biomes only. Ocean/beach/peaks are derived from elevation, so they are
 * excluded from climate-space blending but still have definitions.
 * @type {ReadonlyArray<BiomeDefinition>}
 */
export const BIOMES = Object.freeze([
  {
    id: Biome.OCEAN,
    name: 'Ocean',
    temperature: 0,
    moisture: 1,
    baseHeight: SEA_LEVEL - 12,
    amplitude: 0.35,
    roughness: 0.6,
    surface: Block.SAND,
    subsurface: Block.SAND,
    subsurfaceDepth: 3,
    tree: TreeType.NONE,
    treeDensity: 0,
    grassDensity: 0,
    flowerDensity: 0,
    snowy: false,
    grassTint: [120, 190, 130],
  },
  {
    id: Biome.BEACH,
    name: 'Beach',
    temperature: 0.3,
    moisture: 0.4,
    baseHeight: SEA_LEVEL + 1,
    amplitude: 0.25,
    roughness: 0.3,
    surface: Block.SAND,
    subsurface: Block.SAND,
    subsurfaceDepth: 4,
    tree: TreeType.NONE,
    treeDensity: 0,
    grassDensity: 0.2,
    flowerDensity: 0,
    snowy: false,
    grassTint: [150, 200, 130],
  },
  {
    id: Biome.PLAINS,
    name: 'Plains',
    temperature: 0.15,
    moisture: -0.05,
    baseHeight: SEA_LEVEL + 5,
    amplitude: 0.55,
    roughness: 0.5,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 4,
    tree: TreeType.OAK,
    treeDensity: 0.6,
    grassDensity: 14,
    flowerDensity: 3,
    snowy: false,
    grassTint: [142, 197, 92],
  },
  {
    id: Biome.FOREST,
    name: 'Forest',
    temperature: 0.05,
    moisture: 0.5,
    baseHeight: SEA_LEVEL + 7,
    amplitude: 0.8,
    roughness: 0.7,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 4,
    tree: TreeType.OAK,
    treeDensity: 7,
    grassDensity: 10,
    flowerDensity: 2,
    snowy: false,
    grassTint: [110, 176, 78],
  },
  {
    id: Biome.BIRCH_FOREST,
    name: 'Birch Forest',
    temperature: -0.1,
    moisture: 0.3,
    baseHeight: SEA_LEVEL + 7,
    amplitude: 0.75,
    roughness: 0.65,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 4,
    tree: TreeType.BIRCH,
    treeDensity: 6,
    grassDensity: 9,
    flowerDensity: 4,
    snowy: false,
    grassTint: [132, 189, 96],
  },
  {
    id: Biome.TAIGA,
    name: 'Taiga',
    temperature: -0.55,
    moisture: 0.45,
    baseHeight: SEA_LEVEL + 9,
    amplitude: 1,
    roughness: 0.85,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 3,
    tree: TreeType.SPRUCE,
    treeDensity: 8,
    grassDensity: 5,
    flowerDensity: 0.5,
    snowy: false,
    grassTint: [104, 158, 104],
  },
  {
    id: Biome.SNOWY_PLAINS,
    name: 'Snowy Plains',
    temperature: -0.9,
    moisture: 0,
    baseHeight: SEA_LEVEL + 5,
    amplitude: 0.5,
    roughness: 0.45,
    surface: Block.SNOWY_GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 4,
    tree: TreeType.SPRUCE,
    treeDensity: 0.8,
    grassDensity: 1,
    flowerDensity: 0,
    snowy: true,
    grassTint: [160, 190, 170],
  },
  {
    id: Biome.DESERT,
    name: 'Desert',
    temperature: 0.9,
    moisture: -0.85,
    baseHeight: SEA_LEVEL + 4,
    amplitude: 0.6,
    roughness: 0.55,
    surface: Block.SAND,
    subsurface: Block.SANDSTONE,
    subsurfaceDepth: 5,
    tree: TreeType.CACTUS,
    treeDensity: 1.6,
    grassDensity: 0.6,
    flowerDensity: 0,
    snowy: false,
    grassTint: [190, 180, 110],
  },
  {
    id: Biome.SAVANNA,
    name: 'Savanna',
    temperature: 0.75,
    moisture: -0.3,
    baseHeight: SEA_LEVEL + 6,
    amplitude: 0.65,
    roughness: 0.5,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 4,
    tree: TreeType.ACACIA,
    treeDensity: 1.2,
    grassDensity: 16,
    flowerDensity: 1,
    snowy: false,
    grassTint: [176, 190, 96],
  },
  {
    id: Biome.ROCKY_HILLS,
    name: 'Rocky Hills',
    temperature: -0.2,
    moisture: -0.5,
    baseHeight: SEA_LEVEL + 20,
    amplitude: 1.5,
    roughness: 1.1,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 2,
    tree: TreeType.SPRUCE,
    treeDensity: 2,
    grassDensity: 4,
    flowerDensity: 1,
    snowy: false,
    grassTint: [122, 168, 100],
  },
  {
    id: Biome.MOUNTAINS,
    name: 'Mountains',
    temperature: -0.4,
    moisture: 0.1,
    baseHeight: SEA_LEVEL + 34,
    amplitude: 2.4,
    roughness: 1.3,
    surface: Block.STONE,
    subsurface: Block.STONE,
    subsurfaceDepth: 3,
    tree: TreeType.SPRUCE,
    treeDensity: 0.6,
    grassDensity: 1,
    flowerDensity: 0,
    snowy: false,
    grassTint: [130, 165, 120],
  },
  {
    id: Biome.SNOWY_PEAKS,
    name: 'Snowy Peaks',
    temperature: -1,
    moisture: 0.2,
    baseHeight: SEA_LEVEL + 46,
    amplitude: 2.6,
    roughness: 1.4,
    surface: Block.SNOW_BLOCK,
    subsurface: Block.STONE,
    subsurfaceDepth: 3,
    tree: TreeType.NONE,
    treeDensity: 0,
    grassDensity: 0,
    flowerDensity: 0,
    snowy: true,
    grassTint: [190, 210, 210],
  },
  ...EXTRA_BIOMES,
  // Phase 4. Appended, never inserted: an id already stored in a save file has
  // to keep meaning the same biome. These are excluded from CLIMATE_BIOMES
  // below, so Overworld generation is unaffected.
  ...NETHER_BIOME_DEFINITIONS,
]);

/** Definitions indexed by biome id. */
const BIOME_BY_ID = BIOMES.reduce((array, definition) => {
  array[definition.id] = definition;
  return array;
}, /** @type {BiomeDefinition[]} */ ([]));

/**
 * Biomes that participate in climate-space blending. Ocean, beach and peaks are
 * assigned by elevation instead.
 */
const CLIMATE_BIOMES = BIOMES.filter(
  (definition) =>
    !definition.underground &&
    // Nether biomes live in the same table so that biome ids stay globally
    // unique, but they are chosen by NetherGenerator, never blended here.
    !definition.nether &&
    definition.id !== Biome.OCEAN &&
    definition.id !== Biome.BEACH &&
    definition.id !== Biome.SNOWY_PEAKS
);

/** Y level at which permanent snow begins, before temperature adjustment. */
const SNOW_LINE = SEA_LEVEL + 38;
/** Height above which surfaces turn to bare stone. */
const STONE_LINE = SEA_LEVEL + 30;

/**
 * @typedef {Object} ColumnSample
 * @property {number} height Y of the highest generated terrain block.
 * @property {number} biome Biome id.
 * @property {number} temperature
 * @property {number} moisture
 * @property {number} continentalness
 * @property {number} erosion
 * @property {number} surface Surface block id.
 * @property {number} subsurface Subsurface block id.
 * @property {number} subsurfaceDepth
 * @property {boolean} underwater True when the surface is below sea level.
 * @property {boolean} snowy
 */

export class BiomeGenerator {
  /**
   * @param {number} seed
   */
  constructor(seed) {
    this.seed = seed >>> 0;
    this._noise = new NoiseSet(this.seed, [
      'continental',
      'erosion',
      'hills',
      'ridge',
      'temperature',
      'moisture',
      'warp',
      'detail',
      'beach',
    ]);

    /** Reused sample object for the hot path. */
    this._sample = createColumnSample();
    /** Scratch weight buffer, one slot per climate biome. */
    this._weights = new Float64Array(CLIMATE_BIOMES.length);
  }

  /**
   * Full climate + landform sample for a world column.
   *
   * @param {number} worldX
   * @param {number} worldZ
   * @param {ColumnSample} [out] Optional target to avoid allocation.
   * @returns {ColumnSample}
   */
  sampleColumn(worldX, worldZ, out = this._sample) {
    const continental = this._noise.get('continental');
    const erosionNoise = this._noise.get('erosion');
    const hillsNoise = this._noise.get('hills');
    const ridgeNoise = this._noise.get('ridge');
    const warpNoise = this._noise.get('warp');
    const detailNoise = this._noise.get('detail');

    // --- domain warp -------------------------------------------------------
    // Offsetting the sample point by low-frequency noise makes coastlines and
    // biome edges meander instead of following the noise grid.
    const warpX = warpNoise.noise2(worldX * 0.0009, worldZ * 0.0009) * 48;
    const warpZ = warpNoise.noise2(worldX * 0.0009 + 7.31, worldZ * 0.0009 - 3.17) * 48;
    const wx = worldX + warpX;
    const wz = worldZ + warpZ;

    // --- landform fields ---------------------------------------------------
    // Continentalness: very low frequency, decides land vs. sea.
    const continentalness = continental.fbm2(wx, wz, 4, 0.00042, 2.1, 0.5);
    // Erosion: high erosion flattens terrain, low erosion lets relief through.
    const erosion = erosionNoise.fbm2(wx, wz, 3, 0.0011, 2.0, 0.5);
    // Hilliness: mid-frequency rolling relief.
    const hills = hillsNoise.fbm2(wx, wz, 4, 0.0055, 2.0, 0.5);
    // Ridges: sharp mountain spines, masked so they only appear inland.
    const ridge = ridgeNoise.ridged2(wx, wz, 4, 0.0026, 2.05, 0.5) * 2 - 1;

    // --- climate fields ----------------------------------------------------
    let temperature = this._noise.get('temperature').fbm2(wx, wz, 3, 0.00058, 2.0, 0.5) * 1.35;
    let moisture = this._noise.get('moisture').fbm2(wx, wz, 3, 0.00071, 2.0, 0.5) * 1.35;
    temperature = clamp(temperature, -1, 1);
    moisture = clamp(moisture, -1, 1);

    // --- blended height ----------------------------------------------------
    // Relief is shared across biomes so a blend of two biomes never produces a
    // step; only the amplitude and target height differ per biome.
    const erosionFactor = lerp(1, 0.28, clamp01((erosion + 1) * 0.5));
    const inlandMask = smoothstep(-0.08, 0.42, continentalness);
    const relief =
      hills * 9 * erosionFactor + Math.max(0, ridge) * 26 * inlandMask * erosionFactor;

    const weights = this._weights;
    let weightSum = 0;
    for (let i = 0; i < CLIMATE_BIOMES.length; i++) {
      const definition = CLIMATE_BIOMES[i];
      const dt = temperature - definition.temperature;
      const dm = moisture - definition.moisture;
      // Inverse square distance with a floor: nearby biomes dominate, distant
      // ones still contribute a little, and nothing divides by zero.
      const weight = 1 / (dt * dt + dm * dm + 0.035) ** 1.9;
      weights[i] = weight;
      weightSum += weight;
    }

    let blendedBase = 0;
    let blendedAmplitude = 0;
    let blendedRoughness = 0;
    let dominantIndex = 0;
    let dominantWeight = -1;
    for (let i = 0; i < CLIMATE_BIOMES.length; i++) {
      const normalised = weights[i] / weightSum;
      const definition = CLIMATE_BIOMES[i];
      blendedBase += definition.baseHeight * normalised;
      blendedAmplitude += definition.amplitude * normalised;
      blendedRoughness += definition.roughness * normalised;
      if (weights[i] > dominantWeight) {
        dominantWeight = weights[i];
        dominantIndex = i;
      }
    }

    // Ocean basins: pull the whole column down where continentalness is low.
    const oceanDepth = smoothstep(0.05, -0.55, continentalness);
    const landHeight = blendedBase + relief * blendedAmplitude;
    const oceanFloor = SEA_LEVEL - 6 - 26 * oceanDepth + hills * 4;
    let height = lerp(landHeight, oceanFloor, oceanDepth);

    // Small-scale detail so flat biomes are not billiard tables.
    height += detailNoise.fbm2(wx, wz, 3, 0.045, 2.0, 0.5) * 1.6 * blendedRoughness;

    height = Math.round(clamp(height, 2, WORLD_HEIGHT - 12));

    // --- classification ----------------------------------------------------
    let biomeId = CLIMATE_BIOMES[dominantIndex].id;
    const underwater = height < SEA_LEVEL;

    if (height <= SEA_LEVEL - 3) {
      if (oceanDepth > 0.72) biomeId = Biome.DEEP_OCEAN;
      else if (temperature < -0.65) biomeId = Biome.FROZEN_OCEAN;
      else if (temperature < -0.25) biomeId = Biome.COLD_OCEAN;
      else if (temperature > 0.65) biomeId = Biome.WARM_OCEAN;
      else if (temperature > 0.25) biomeId = Biome.LUKEWARM_OCEAN;
      else biomeId = Biome.OCEAN;
    } else if (height <= SEA_LEVEL + 1) {
      // Only sand the shoreline where the land is genuinely low and flat; a
      // cliff dropping into the sea should stay stone.
      const beachiness = this._noise.get('beach').noise2(worldX * 0.02, worldZ * 0.02);
      if (beachiness > -0.35) biomeId = Biome.BEACH;
    } else if (height >= STONE_LINE) {
      const snowBias = SNOW_LINE - temperature * 14;
      biomeId = height >= snowBias ? Biome.SNOWY_PEAKS : Biome.MOUNTAINS;
    }

    const definition = BIOME_BY_ID[biomeId];

    out.height = height;
    out.biome = biomeId;
    out.temperature = temperature;
    out.moisture = moisture;
    out.continentalness = continentalness;
    out.erosion = erosion;
    out.surface = definition.surface;
    out.subsurface = definition.subsurface;
    out.subsurfaceDepth = definition.subsurfaceDepth;
    out.underwater = underwater;
    out.snowy = definition.snowy || (height > SNOW_LINE - temperature * 14 && temperature < 0.1);
    return out;
  }

  /**
   * Surface height only. Structures need heights outside the chunk they are
   * decorating, and this keeps that call site honest about the cost.
   *
   * @param {number} worldX
   * @param {number} worldZ
   * @returns {number}
   */
  getSurfaceHeight(worldX, worldZ) {
    return this.sampleColumn(worldX, worldZ, this._sample).height;
  }
}

/** Biome definition lookup by id. */
export function getBiome(id) {
  return BIOME_BY_ID[id] || BIOME_BY_ID[Biome.PLAINS];
}

/** Display name for a biome id. */
export function getBiomeName(id) {
  return BIOME_BY_ID[id]?.name ?? 'Unknown';
}

/** Allocates a fresh column sample object. */
export function createColumnSample() {
  return {
    height: SEA_LEVEL,
    biome: Biome.PLAINS,
    temperature: 0,
    moisture: 0,
    continentalness: 0,
    erosion: 0,
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    subsurfaceDepth: 4,
    underwater: false,
    snowy: false,
  };
}

export default BiomeGenerator;
